// Package planner implements a Planner-Executor dual-agent architecture.
// The Planner generates a structured JSON execution plan (with step dependencies),
// and the Executor runs steps in topological order, supporting revision on failure.
package planner

import (
	"context"
	"encoding/json"
	"fmt"
	"sort"
	"strings"
	"time"

	"go.uber.org/zap"
)

// ─── Plan Data Structures ───────────────────────────────────────────────────

// Plan represents a structured execution plan generated by the Planner LLM.
type Plan struct {
	ID        string     `json:"id"`
	Goal      string     `json:"goal"`
	Steps     []Step     `json:"steps"`
	Reasoning string     `json:"reasoning"`
	CreatedAt time.Time  `json:"created_at"`
	RevisedAt *time.Time `json:"revised_at,omitempty"`
	Version   int        `json:"version"`
}

// Step is a single action in the execution plan with dependency tracking.
type Step struct {
	ID          string          `json:"id"`
	Action      string          `json:"action"`      // e.g. "read_file", "write_file", "execute_code", "search_code"
	Description string          `json:"description"` // human-readable explanation
	Parameters  json.RawMessage `json:"parameters,omitempty"`
	DependsOn   []string        `json:"depends_on,omitempty"` // IDs of prerequisite steps
	Status      StepStatus      `json:"status"`
	Output      string          `json:"output,omitempty"`
	Error       string          `json:"error,omitempty"`
	Duration    time.Duration   `json:"duration,omitempty"`
}

// StepStatus tracks the lifecycle of a plan step.
type StepStatus string

const (
	StepPending   StepStatus = "pending"
	StepRunning   StepStatus = "running"
	StepCompleted StepStatus = "completed"
	StepFailed    StepStatus = "failed"
	StepSkipped   StepStatus = "skipped"
)

// ─── Planner ────────────────────────────────────────────────────────────────

// LLMCaller abstracts LLM interaction for testability.
type LLMCaller interface {
	Call(ctx context.Context, systemPrompt, userPrompt string) (string, error)
}

// Planner generates and revises execution plans via LLM.
type Planner struct {
	llm    LLMCaller
	logger *zap.Logger
}

// NewPlanner creates a new Planner instance.
func NewPlanner(llm LLMCaller, logger *zap.Logger) *Planner {
	return &Planner{llm: llm, logger: logger}
}

const plannerSystemPrompt = `You are a planning agent. Given a user's coding task, produce a JSON execution plan.

Rules:
1. Break the task into discrete steps. Each step has an "id" (like "step_1"), "action" (tool name), "description", optional "parameters", and "depends_on" (list of prerequisite step IDs).
2. Steps with no dependencies can run in parallel.
3. Use actions: read_file, write_file, edit_file, execute_code, search_code, run_tests, think.
4. The plan should be minimal but complete — don't add unnecessary steps.
5. Output ONLY valid JSON matching this schema:
{
  "goal": "string",
  "reasoning": "string explaining your approach",
  "steps": [
    {"id": "step_1", "action": "read_file", "description": "...", "parameters": {...}, "depends_on": []},
    {"id": "step_2", "action": "edit_file", "description": "...", "parameters": {...}, "depends_on": ["step_1"]}
  ]
}`

// CreatePlan asks the LLM to generate an execution plan for the given task.
func (p *Planner) CreatePlan(ctx context.Context, task string, contextInfo string) (*Plan, error) {
	userPrompt := fmt.Sprintf("Task: %s", task)
	if contextInfo != "" {
		userPrompt += fmt.Sprintf("\n\nContext:\n%s", contextInfo)
	}

	raw, err := p.llm.Call(ctx, plannerSystemPrompt, userPrompt)
	if err != nil {
		return nil, fmt.Errorf("planner LLM call failed: %w", err)
	}

	plan, err := parsePlanJSON(raw)
	if err != nil {
		return nil, fmt.Errorf("failed to parse plan: %w", err)
	}

	plan.ID = fmt.Sprintf("plan_%d", time.Now().UnixNano())
	plan.CreatedAt = time.Now()
	plan.Version = 1

	// Validate DAG
	if err := ValidateDAG(plan.Steps); err != nil {
		return nil, fmt.Errorf("invalid plan DAG: %w", err)
	}

	p.logger.Info("plan created",
		zap.String("plan_id", plan.ID),
		zap.Int("steps", len(plan.Steps)),
		zap.String("goal", plan.Goal),
	)
	return plan, nil
}

const revisionSystemPrompt = `You are a planning agent revising an execution plan that encountered failures.

Given the original plan with step statuses and outputs, produce a revised plan.
- Keep completed steps as-is (don't re-run them).
- Fix or replace failed steps.
- Add new steps if the failure reveals missing work.
- Output ONLY valid JSON in the same schema as the original plan.`

// RevisePlan updates a plan after step failures, asking the LLM to adjust.
func (p *Planner) RevisePlan(ctx context.Context, plan *Plan, failureSummary string) (*Plan, error) {
	planJSON, _ := json.MarshalIndent(plan, "", "  ")
	userPrompt := fmt.Sprintf("Current plan state:\n%s\n\nFailure summary:\n%s\n\nPlease revise the plan.", string(planJSON), failureSummary)

	raw, err := p.llm.Call(ctx, revisionSystemPrompt, userPrompt)
	if err != nil {
		return nil, fmt.Errorf("revision LLM call failed: %w", err)
	}

	revised, err := parsePlanJSON(raw)
	if err != nil {
		return nil, fmt.Errorf("failed to parse revised plan: %w", err)
	}

	now := time.Now()
	revised.ID = plan.ID
	revised.CreatedAt = plan.CreatedAt
	revised.RevisedAt = &now
	revised.Version = plan.Version + 1

	if err := ValidateDAG(revised.Steps); err != nil {
		return nil, fmt.Errorf("invalid revised plan DAG: %w", err)
	}

	p.logger.Info("plan revised",
		zap.String("plan_id", revised.ID),
		zap.Int("version", revised.Version),
		zap.Int("steps", len(revised.Steps)),
	)
	return revised, nil
}

// ─── DAG Validation & Topological Sort ──────────────────────────────────────

// ValidateDAG checks that the steps form a valid directed acyclic graph.
func ValidateDAG(steps []Step) error {
	ids := make(map[string]bool, len(steps))
	for _, s := range steps {
		if ids[s.ID] {
			return fmt.Errorf("duplicate step ID: %s", s.ID)
		}
		ids[s.ID] = true
	}
	for _, s := range steps {
		for _, dep := range s.DependsOn {
			if !ids[dep] {
				return fmt.Errorf("step %q depends on unknown step %q", s.ID, dep)
			}
			if dep == s.ID {
				return fmt.Errorf("step %q depends on itself", s.ID)
			}
		}
	}
	// Check for cycles using topological sort
	_, err := TopologicalSort(steps)
	return err
}

// TopologicalSort returns steps in a valid execution order (Kahn's algorithm).
// Steps at the same level (no mutual dependencies) are grouped together.
func TopologicalSort(steps []Step) ([][]Step, error) {
	if len(steps) == 0 {
		return nil, nil
	}

	// Build adjacency + in-degree
	inDegree := make(map[string]int, len(steps))
	dependents := make(map[string][]string, len(steps))
	stepMap := make(map[string]*Step, len(steps))

	for i := range steps {
		s := &steps[i]
		stepMap[s.ID] = s
		inDegree[s.ID] = len(s.DependsOn)
		for _, dep := range s.DependsOn {
			dependents[dep] = append(dependents[dep], s.ID)
		}
	}

	// Find all roots (in-degree 0)
	var queue []string
	for id, deg := range inDegree {
		if deg == 0 {
			queue = append(queue, id)
		}
	}
	sort.Strings(queue) // deterministic ordering

	var levels [][]Step
	processed := 0

	for len(queue) > 0 {
		// Current level: all items in queue can run in parallel
		level := make([]Step, 0, len(queue))
		var nextQueue []string

		for _, id := range queue {
			level = append(level, *stepMap[id])
			processed++

			for _, depID := range dependents[id] {
				inDegree[depID]--
				if inDegree[depID] == 0 {
					nextQueue = append(nextQueue, depID)
				}
			}
		}

		levels = append(levels, level)
		sort.Strings(nextQueue)
		queue = nextQueue
	}

	if processed != len(steps) {
		return nil, fmt.Errorf("cycle detected in step dependencies: processed %d of %d steps", processed, len(steps))
	}

	return levels, nil
}

// ─── Plan Summary ───────────────────────────────────────────────────────────

// Summary returns a human-readable summary of the plan for display.
func (p *Plan) Summary() string {
	var sb strings.Builder
	sb.WriteString(fmt.Sprintf("## Plan: %s (v%d)\n", p.Goal, p.Version))
	sb.WriteString(fmt.Sprintf("**Reasoning**: %s\n\n", p.Reasoning))

	for i, s := range p.Steps {
		status := statusEmoji(s.Status)
		deps := ""
		if len(s.DependsOn) > 0 {
			deps = fmt.Sprintf(" (after: %s)", strings.Join(s.DependsOn, ", "))
		}
		sb.WriteString(fmt.Sprintf("%d. %s [%s] %s%s\n", i+1, status, s.Action, s.Description, deps))
	}
	return sb.String()
}

func statusEmoji(s StepStatus) string {
	switch s {
	case StepCompleted:
		return "✅"
	case StepFailed:
		return "❌"
	case StepRunning:
		return "🔄"
	case StepSkipped:
		return "⏭️"
	default:
		return "⬜"
	}
}

// CompletedStepIDs returns IDs of all completed steps.
func (p *Plan) CompletedStepIDs() []string {
	var ids []string
	for _, s := range p.Steps {
		if s.Status == StepCompleted {
			ids = append(ids, s.ID)
		}
	}
	return ids
}

// FailedSteps returns all failed steps.
func (p *Plan) FailedSteps() []Step {
	var failed []Step
	for _, s := range p.Steps {
		if s.Status == StepFailed {
			failed = append(failed, s)
		}
	}
	return failed
}

// IsComplete returns true if all steps are completed or skipped.
func (p *Plan) IsComplete() bool {
	for _, s := range p.Steps {
		if s.Status != StepCompleted && s.Status != StepSkipped {
			return false
		}
	}
	return true
}

// ─── JSON Parsing ───────────────────────────────────────────────────────────

// parsePlanJSON extracts a Plan from LLM output, handling markdown code fences.
func parsePlanJSON(raw string) (*Plan, error) {
	// Strip markdown code fences if present
	cleaned := raw
	if idx := strings.Index(cleaned, "```json"); idx >= 0 {
		cleaned = cleaned[idx+7:]
	} else if idx := strings.Index(cleaned, "```"); idx >= 0 {
		cleaned = cleaned[idx+3:]
	}
	if idx := strings.LastIndex(cleaned, "```"); idx >= 0 {
		cleaned = cleaned[:idx]
	}
	cleaned = strings.TrimSpace(cleaned)

	var plan Plan
	if err := json.Unmarshal([]byte(cleaned), &plan); err != nil {
		return nil, fmt.Errorf("JSON parse error: %w (raw: %.200s)", err, raw)
	}

	// Default all steps to pending
	for i := range plan.Steps {
		if plan.Steps[i].Status == "" {
			plan.Steps[i].Status = StepPending
		}
	}

	return &plan, nil
}
